
export const ActionTypes = {
    SET_PRODCUTS: 'SET_PRODCUTS',
    SELECTED_PRODECUTS: 'SELECTED_PRODECUTS',
    REMOVE_SELECTED_PRODCUTS: 'REMOVE_SELECTED_PRODCUTS',
    FETCH_PRODCUTS: 'FETCH_PRODCUTS'
}

export const MoviesTypes = {
    GET_MOVIES: 'GET_MOVIES',
    MOVIES_DETAILS: 'MOVIES_DETAILS',
    SEARCH_RESULTS: 'SEARCH_RESULTS',
    SIMILAR_MOVIES: 'SIMILAR_MOVIES',
}